### ISSUE TITLE
Huge gif image causes git and plugin managers to fail

### ISSUE THREAD

**Issue by rafi** [shime/vim-livedown#13]
Commit 2580179f introduces a huge gif file, **4.5mb**, even though commit d1b7a04e removes that gif, it is still stored in git's history and causes a fresh git clone to take ages, and under certain internet connections - fail.

To completely remove `demo.gif` from Git history, you'll need to rewrite the tree:
```sh
git filter-branch --tree-filter 'rm -f demo.gif' HEAD
git gc
git push --force
```

**Comment by shime** [comment]
Hm, yeah I've noticed that. Thought it would not be a problem since you can avoid it by just cloning with `git clone --depth 1` to avoid it, if you're worried about the size. 

Rewriting history is something I would avoid all the time, but since there is no external package manager (like npm) being used here, things will not get too messy if I did that. 

I'll think about it after I before I release the new version, thanks.

**Comment by shime** [comment]
I've just rewritten the tree with the commands you've specified, but unfortunately the repo size remains the same.

**Comment by john-kurkowski** [comment]
D'oh! And now vim-plug can't fast forward to the latest version. Users will have to uninstall vim-livedown and reinstall.

**Comment by shime** [comment]
Just rewritten the entire history of this repo to shrink its size. Sorry for the mess.
