### ISSUE TITLE
Show vim cursor in preview?

### ISSUE THREAD

**Issue by mehultikekar** [shime/vim-livedown#15]
Is this possible? It would make it easier to type while looking at the browser rather than the vim window.

**Comment by shime** [comment]
Sorry, but no. Livedown is intended to serve as a tool for in-browser previewing the markdown you type in the editor and will not be a replacement for those editors.

**Comment by towc** [comment]
There's a chance this was slightly misunderstood.

I'm running into the same thing, where I got a setup that writes the file every time I type anything, so I get a live-preview in the browser as I'm editing. It works great, except I find myself looking at the browser on one half of the screen, to see what things look like, and when I'm trying to do vim movements, I get slightly lost.

What would be awesome is if there's an indication of where the cursor is, even if **I'm still using vim from the terminal**. This would be a settable option, that might do something as simple as putting a "**|**" at that position, even if it might not look great, because all characters after it would get shifted. It would still be a great help.

If this is how you understood it, then I apologize. If anything this will be yet another deterrent for future people that want this, so they don't start another issue.

Loving the tool, thanks for the work :)
